### ISSUE TITLE
Plugins tab hangs with message "loading"

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#1]
I download from master. Named to oldGregg and copied the folder to plugins/themes.
When I went to settings - website - plugins, there is a spinning wheel with message "loading" and nothing happens.
Following is the error-log message:
"Cannot declare class ArticleSection, because the name is already in use in \\plugins\\themes\\oldGregg\\jatsParser\\classes\\ArticleSection.inc.php on line 14"

**Comment by anupent** [comment]
My mistake.
I deactivated jatsParser plugin and manuscriptJats theme and deleted both folders.
Then I copied oldGregg folder to plugin/theme.
Then I was able to load the plugins tab.

Cheers

**Comment by Vitaliy-1** [comment]
It shares the same PHP classes as jatsParser, so they cannot be used both.

**Comment by farhad425** [comment]
Please write me how to deactivate the jatsParser plugin and manuscriptJats theme. I tried to deactivate them but did not find the Installed Plugin or Plugin Gallery option. I also tried to find them public_html plugin folder but did not find. You help will be highly appreciated.

**Comment by anupent** [comment]
Hi @farhad425 ,
JatsParser plugin folder should be found at ```public_html\plugins\generic``` folder.
Just delete the folder.
You don't need to delete manuscriptJats theme. Just deactivate from the ```plugins``` tab in website setting.
Then copy the oldGregg them folder to ```public_html\plugins\themes``` folder. Active the new theme from ```plugins``` tab in website setting. Then, apply the theme from ```website -> appearance```.

Best regards.

**Comment by farhad425** [comment]
Thank you for your prompt reply.
