### ISSUE TITLE
Add footer to the article detail page

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#10]
Was there any reason not to include footer in article detail page?

I think, it would be good to have footer there.

**Comment by Vitaliy-1** [comment]
The main elements there (left and right blocks) have absolute positioning. If we add a page-width footer, it would occupy too much space because also needs absolute positioning. So we can inject footer only in the left block.

**Comment by anupent** [comment]
I tried this patch. Footer is present only in the left block. Looks awkward (May need some time for eyes to accomodate).
What if I choose not to install this footer when I upgrade this plugin?
