### ISSUE TITLE
Problems on version: 3.1.2.0  

### ISSUE THREAD

**Issue by JamieFowlie** [Vitaliy-1/oldGregg#106]
When I upload and activate the oldgregg theme, the site crashes. I have to delete and resort back to default theme. 

Is there a step by step set of instrucions to move from default to oldGrgg that I can read?

My steps;
Upload oldgregg to /plugins/themes/ 
Activate oldGregg in plugin manager
Deactivate default in plugin manager

Make sure OldGregg is in Appearance
Manually delete cahce files from t_cache

Visit website. Totallty crashed.

I see that the JatsParser folder inside oldgregg folder is empty.  Any required configurations or uploads before I move forward?

Thanks, in advance

**Comment by Vitaliy-1** [comment]
Hi @JamieFowlie, if you are working with Git directly, make sure you've installed submodules as well: git submodule update --init --recursive. Otherwise just download the latest release.

**Comment by JamieFowlie** [comment]
Thanks. The file download contains an empty JatsParser. Downloading separately this folder from the Git and uploading the content to the subfolder in oldGregg solved the problem
