### ISSUE TITLE
Dear Dr. Vitaliy. I can not download fully oldGreed theme files, could you please help me.

### ISSUE THREAD

**Issue by ddhung81** [Vitaliy-1/oldGregg#107]
Dear Dr. Vitaliy.
I can not download fully oldGreed theme files, could you please help me.
![image](https://user-images.githubusercontent.com/33564137/58607618-881b3580-82ca-11e9-8d69-2b1dba1ff0bd.png)

**Comment by Vitaliy-1** [comment]
E.g., with git: clone the repository and install submodules.

**Comment by ddhung81** [comment]
Thank so much Dr. Vitaliy

**Comment by ddhung81** [comment]
Dear Dr. Vitaliy,
OldGregg theme not work on OJS 3.1.2 (Window 10; Wampserver 3.1.9; PHP 7.3.5)
Could you help me solving problem. I look forward to hearing from you soon. 
Thank you
[php_error.log](https://github.com/Vitaliy-1/oldGregg/files/3239338/php_error.log)

**Comment by Vitaliy-1** [comment]
The error says something about `frontend/components/searchForm_simple.tpl` file but the theme doesn't have it. Maybe you need just to clear the cache? Last time I checked the theme worked successfully with OHS 3.1.2-1.

Also, you can try to download the master branch of the theme directly from Git:
 `git clone --recurse-submodules https://github.com/Vitaliy-1/oldGregg.git`
