### ISSUE TITLE
Запрос

### ISSUE THREAD

**Issue by tuskov** [Vitaliy-1/oldGregg#108]
Добрый день, Виталий. На русском можно писать?

**Comment by Vitaliy-1** [comment]
Можно

**Comment by tuskov** [comment]
Добрый день, Виталий. Вы можете помочь с настройкой OJS после обновления? Готов обсудить условия. Сайт fortus-science.ru

**Comment by Vitaliy-1** [comment]
Вряд ли сейчас у меня найдется время. А есть какая-то конкретная проблема? Как вариант можете открить тему на форуме: https://forum.pkp.sfu.ca/
