### ISSUE TITLE
Error on extracting Editor from JATS file ?

### ISSUE THREAD

**Issue by navotera** [Vitaliy-1/oldGregg#109]
Hi Dr. Vitaliy

Thank for your nice theme. 

I found error on JATS parser when try to parse or extract editor. I am using JATS file as attached. Can you help to point out why it happen ? 

I check that the function that extracting the editorial list exactly on this location : 
![image](https://user-images.githubusercontent.com/1424851/60395751-d1c99b00-9b6a-11e9-97de-654ab87dbb9c.png)

JATS file :
https://pastebin.com/rB8pANPC

Thank

**Comment by Vitaliy-1** [comment]
Hi @navotera,

The problem is probably in empty tag on line 753: ` <person-group person-group-type="editor"/>` and line 829: `<person-group person-group-type="editor"/>`
They are prematurely closed. Can you correct it and tell if it fixes the problem?

**Comment by navotera** [comment]
Hi Dr. Vitaliy

Thank you for your response. I can confirm that your solution is working. 
For the detail previously I adding the closing tag for the editor group tag but seem like I only close for one tag on which that the XML file need all the tag should be closed. 

**Thank you for your solution and all your awesome plugin.**
