### ISSUE TITLE
 {call_hook name="Templates::Article::Details"} when placed inside the template of article_details page, the page gives 505 error 

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#116]
{call_hook name="Templates::Article::Details"} when placed inside the template of article_details page (some plugins are attached/arrayed to it), the page gives 505 error

**Comment by Vitaliy-1** [comment]
Hmm, this is probably because of an incorrect URL or th browser doesn't support HTTP protocol version.
I'm currently working on a new release on dev branch together with the new version of JATS Parser Plugin. If the error persists there, I'll take a look.
