### ISSUE TITLE
All TCPDF rendered links are broken on demo site 

### ISSUE THREAD

**Issue by ericfrancisco** [Vitaliy-1/oldGregg#120]
I'm having trouble getting the TCPDF rendering to load the images in my rendered pdf, all appears correct in the rendered HTML from the XML.  

In researching this I noticed that only your embedded PDF links are working on the oldgregg demo site, all the others just HTTP 500 or hang on a ?CREATE_PDF_QUERY page.

Example: http://ojsdemo.e-medjournal.com/index.php/oldGregg/article/view/5

**Comment by ericfrancisco** [comment]
It appears that TCPDF is missing from the vendor folder?

**Comment by Vitaliy-1** [comment]
Thanks! I'll check. Most probably I'll install the 2.0 beta version on the demo instance in a next few weeks.

**Comment by ericfrancisco** [comment]
Do you plan on re-enabling XML->HTML conversion?  Or is the new beta only going to display abstracts?

**Comment by Vitaliy-1** [comment]
Hi @ericfrancisco,

Yes, but it will be handled by JATS Parser Plugin. It will inject full-text on the article landing page through a hook. Most probably in the next release. Also, article's full-text is going to be a property of a publication, just like the metadata (abstract, title, etc.).

**Comment by ericfrancisco** [comment]
Sounds fantastic, can't wait. 👍
