### ISSUE TITLE
Announcement could not be disabled

### ISSUE THREAD

**Issue by kwahyu** [Vitaliy-1/oldGregg#121]
Dear @Vitaliy-1 
For the beta release of new OldGregg, announcement still pop up in the indexJournal page although it has been disabled (Unchecked Enable announcement) in the website setting.

**Comment by Vitaliy-1** [comment]
Hi @kwahyu,

Does the problem persist in the latest release?

**Comment by kwahyu** [comment]
No, it is resolved.
