### ISSUE TITLE
White page in Home Page

### ISSUE THREAD

**Issue by andisetyaji** [Vitaliy-1/oldGregg#132]
Hello Prof @Vitaly, 

My OJS 3.2.1.1 home page cannot be acces, only homepage. 

in error log : 

[31-Jul-2021 15:08:41 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedFullTitle() on null in /home/=username=/public_html/plugins/themes/oldGregg/OldGreggThemePlugin.inc.php:227
Stack trace:
#0 /home/=username=/public_html/lib/pkp/classes/cache/GenericCache.inc.php(63): OldGreggThemePlugin->_toCache(Object(FileCache), NULL)
#1 /home/=username=/public_html/lib/pkp/classes/cache/FileCache.inc.php(115): GenericCache->get(NULL)
#2 /home/=username=/public_html/plugins/themes/oldGregg/OldGreggThemePlugin.inc.php(181): FileCache->getContents()
#3 /home/=username=/public_html/lib/pkp/classes/plugins/HookRegistry.inc.php(107): OldGreggThemePlugin->browsePopular('TemplateManager...', Array)
#4 /home/=username=/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(906): HookRegistry::call('TemplateManager...', Array)
#5 /home/=username=/public_html/pages/index/IndexHandler.inc.php(66): PKPTemplateManager->display('frontend/pages/...')
#6 /home/=username=/public_html/lib/pkp/classes/core/PKPRouter.inc.php(391): IndexHandler->index(Array, Obje in /home/=username=/public_html/plugins/themes/oldGregg/OldGreggThemePlugin.inc.php on line 227

can I get help?

my best regards

**Comment by Vitaliy-1** [comment]
Sorry for the late reply.
It's likely the case when the publication was unpublished but the plugin tries to retrieve its data from the cache, I'll take a look.
