### ISSUE TITLE
Header logo image

### ISSUE THREAD

**Issue by bjarman** [Vitaliy-1/oldGregg#137]
Hi!
I have a problem with the header logo image. In OJS default theme the header logo image is responsive. However when I switch to oldGregg theme the header logo image is not responsive but rather the actual image size all the time. Is this a known issue and is there a workaround?
Thanks/Fredrik

**Comment by Vitaliy-1** [comment]
Thanks, @bjarman!

The referenced commit should solve the issue. If you want to test, don't forget to clear the template cache after applying.
Feel free to let me know if the problem still persists after this commit

**Comment by bjarman** [comment]
Hi again! The commit seems to have solved the issue some ways. However I am not sure the logo scales as it should. In another implementation using Bootstrap 4 the logo usually scales and alignes with the navbar. I am unfamiliar with the journal_branding heading that seems to be left adjacent to the navbar. In smaller viewports this makes the hamburger drop below the logo and the register and login links. Also, using a .svg image results in width 0 height 0 which makes the logo not visable.
