### ISSUE TITLE
Error when using php 8.1

### ISSUE THREAD

**Issue by felixhelix** [Vitaliy-1/oldGregg#142]
Hi,

we get the following error when oldGregg is activated after we updated our PHP Version to 8.1:

`Fatal error: Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, class OldGreggThemePlugin does not have a method "htmlDisplay" in /var/www/html/lib/pkp/classes/plugins/HookRegistry.inc.php:107 Stack trace: #0 /var/www/html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1168): HookRegistry::call() #1 /var/www/html/lib/pkp/pages/management/ManagementHandler.inc.php(200): PKPTemplateManager->display() #2 /var/www/html/lib/pkp/pages/management/ManagementHandler.inc.php(67): ManagementHandler->website() #3 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(395): ManagementHandler->settings() #4 /var/www/html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest() #5 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route() #6 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch() #7 /var/www/html/index.php(67): PKPApplication->execute() #8 {main} thrown in /var/www/html/lib/pkp/classes/plugins/HookRegistry.inc.php on`

We run
OJS 3.3.0.8
PHP 8.1.14

Yours,

Felix

**Comment by Vitaliy-1** [comment]
Hi @felixhelix,

Is it a full stack trace? I don't see an origin of the error.
Also, what version of the theme are you using, is it 2.2.0?

**Comment by felixhelix** [comment]
Hi @Vitaliy-1 

Sorry for not checking this first: we used an outdated version. 
I installed 2.2.0 and now it works :)

Thanks,

Felix
