### ISSUE TITLE
Wrong menu is highlighted in Article detail page navigation menu

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#16]
Following images are from oldGregg demo site.
In first image, "Introduction" is clicked; it targets "Introduction" section in the article but "Abstract" menu is highlighted.
![image](https://user-images.githubusercontent.com/15881295/34955624-67fc5146-fa4d-11e7-8300-19f9c06799b9.png)

Similarly, a menu above is wrongly selected.

**Comment by Vitaliy-1** [comment]
What browser are you using?
In my case in Chrome, when I click on the introduction section:
![issue](https://user-images.githubusercontent.com/20665587/35009288-c863c978-fb07-11e7-86e4-28f44dbad6d9.jpg)

**Comment by Vitaliy-1** [comment]
Ahh. I can reproduce it in Firefox. But I am afraid I can't do anything here. It is rather Bootstrap 4 issue with their `Scrollspy` component...

**Comment by Vitaliy-1** [comment]
https://github.com/twbs/bootstrap/issues/25335

**Comment by anupent** [comment]
[https://github.com/pkp/pkp-lib/issues/3273](url)
