### ISSUE TITLE
list within list not displayed

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#17]
Please see the code below. It used to be displayed by jatsParser before. But does not do so now.

Codes:
![image](https://user-images.githubusercontent.com/15881295/34980925-13610402-face-11e7-988b-9142c063792c.png)

by jatsParser in manuscriptJats:
![image](https://user-images.githubusercontent.com/15881295/34980948-25ce01b2-face-11e7-8cc5-c5d944d67949.png)

by oldGregg:
![image](https://user-images.githubusercontent.com/15881295/34980996-46465e58-face-11e7-9bcf-7f73184d00e8.png)

**Comment by Vitaliy-1** [comment]
@anupent 
Think was fixed with this patch. Can you apply changes (only for files inside `parser` dir)? Let me know if it does not solve the issue.

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
Solved.
Thank you.
