### ISSUE TITLE
Wrong "Submitted" and "Published" dates in article detail metadata.

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#18]
Please look into following images for disparity in the dates:

1. See the published date in citation which is correct.
![image](https://user-images.githubusercontent.com/15881295/34992629-e287d806-faf5-11e7-9769-6d79972dfa0f.png)

2. See the submitted date in database:
![image](https://user-images.githubusercontent.com/15881295/34992714-1ecec37e-faf6-11e7-8342-7598ec7c0f90.png)

**Comment by Vitaliy-1** [comment]
Hi @anupent 
I have no idea about this...
As you can see here the code is talking about itself:
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/parser/articleMainText.tpl#L314-L317

**Comment by Vitaliy-1** [comment]
Is this happening only with 1 article?

**Comment by anupent** [comment]
See the images below:
1. When mouse over the third card in this image, it is showing link for article 148.
![image](https://user-images.githubusercontent.com/15881295/35020247-43c8b88a-fb53-11e7-8c9c-33414675339c.png)

Online site confirms this relationship:
![image](https://user-images.githubusercontent.com/15881295/35020298-7bbf578a-fb53-11e7-945e-76b222597e66.png)

Now when I click this card, it points to this; the citation details are of 148 but the article is 125.
![image](https://user-images.githubusercontent.com/15881295/35020381-ecb338c6-fb53-11e7-96b8-468573346494.png)

**Comment by anupent** [comment]
Now, I will delete my database and file folder and reinstall them from online dump/backup. I will later post the results.

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
I think the abstract segment is only mismatched. Can you check the abstract portion in your codes.
In all above, only the abstract were from different articles. The main text and the navigation menu were proper.

**Comment by Vitaliy-1** [comment]
As I can see it is Abstract and all meta-data. And with another theme all works fine?

**Comment by anupent** [comment]
Yup, it works fine with default theme. See below for article 148 and compare with the above image of article 148.

![image](https://user-images.githubusercontent.com/15881295/35025466-da166e6c-fb6d-11e7-94da-292335373fb1.png)

**Comment by Vitaliy-1** [comment]
Can you try this patch?
There is an issue from OJS that I suspect is involved here: https://github.com/pkp/pkp-lib/issues/2527

**Comment by anupent** [comment]
Bravo! 
I disabled the "Recommend Articles by Author" plugin and everything seems to work properly.
Thanks.

**Comment by Vitaliy-1** [comment]
@anupent 
So there is some conflict caused by unexpected interaction with these plugins on the backend. 
Can you try also to change in recommend by author plugin this line:
https://github.com/pkp/ojs/blob/master/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L34
to this:
`HookRegistry::register('Templates::Article::Footer::PageFooter', array($this, 'callbackTemplateArticlePageFooter'), HOOK_SEQUENCE_LATE);`
and check if it solves the problem?

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
Above patch does not solve the problem.
