### ISSUE TITLE
Styles is not applied to website

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#2]
I uninstalled "jatsParser plugin" and "manuscript-Jats" theme plugin. Then I copied the oldGregg folder to /plugins/themes folder and activated it in the settings - website - plugins.

When I load my homepage, styles do not seem to be applied. Below is the printscreen image:

![image](https://user-images.githubusercontent.com/15881295/34719976-0cd0be52-f565-11e7-9027-529eac22a0e0.png)

I tried removing my custom stylesheet from public folder. Same results. 
However, when I again copy manuscriptJats folder into theme, style is properly applied even if manuscriptJats them is not activated under plugins in website settings.

I am using OJS 3.1.0.1 with following server info:

OS platform | WINNT
PHP version | 7.1.10
Apache version | Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10
Database driver | mysqli
Database server version | 10.1.28-MariaDB

**Comment by Vitaliy-1** [comment]
Hi @anupent 
What errors do you see in the PHP logs?
Have you cleared the template cache after changing the theme?

**Comment by Vitaliy-1** [comment]
From the screenshot, it can be seen that indexJournal template is not from the oldGregg theme. Suppose it is compiled template from the previous theme. So, the most obvious solution is to clear template cache from admin area in the dashboard or manually from the cache folder. 

There shouldn't be any problem with PHP version as demonstration journal uses the same.

**Comment by anupent** [comment]
Dear @Vitaliy-1 ,
I cleared template cache and browser cache after changing the theme. Still problem persists. And there are no fatal errors in the PHP logs. 
If I drag my manuscriptJats folder to the theme folder, home page loads with proper styling. However, article detail page looks like this:
![image](https://user-images.githubusercontent.com/15881295/34731051-4232a0d2-f589-11e7-81fc-4175d81cdaea.png)

I will now do a fresh installation of OJS as trial and activate this theme and see whether it works.

@anupent

**Comment by Vitaliy-1** [comment]
Hi @anupent 
Article landing page from the screenshot above is certainly not from oldGregg theme. If there isn't any errors in the PHP log, maybe the problem is in the browser cache? (ctrl + F5 to clear)
Is the oldGregg theme activated? 
Is the JATS Parser Plugin deactivated (it's looks like CSS from this plugin is still applied to the article detail page)?
Can you view through browser inspect what CSS files are downloaded on the page? It should only from:
`http://yourdomain.com/plugins/themes/oldGregg/...` (not from other directories!) -> again, CTRL + F5 is to clear browser cache of the current page.

I have already tested the theme on 2 OJS instances, on own journal and clean OJS 3.1.0-1 install without any issues.

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
I deleted by htdocs folder and copied a new instance of OJS 3.1.0.1. Then I replaced my public folder, config.inc.php. I renamed by custom stylesheet to something else for time being. 
Then I copied oldGregg folder to theme folder (Now there are only two themes, default and oldGress; previously there was a third theme also, manuscript).
When I load my homepage, still I don't get the styles.

Browser console shows, following files being called:
1, /plugins/generic/orcidProfile/css/orcidProfile.css
2, /public/site/sitestyle.css
3, /public/journals/1/styleSheet.css (not available now as i have renamed the filename)
4. https://cdn.jsdelivr.net/emojione/2.2.7/assets/css/emojione.min.css

I dont't see css file being called from themes/oldGregg folder. I think oldGregg theme is not called at all, no css, no jatsParser. 
Now article detail page looks better but I dont see full article; only abstract is visible.
I have activated the oldGregg theme:
![image](https://user-images.githubusercontent.com/15881295/34733117-56c5eda0-f58f-11e7-8d38-180f0220b1e8.png)

confused!

**Comment by Vitaliy-1** [comment]
@anupent 
Is the theme activated from the appearance menu?

**Comment by anupent** [comment]
You got it right.
It had been ages I never changed theme in the appearance menu.
Now it is loading.
Sorry for consuming your time for my silly mistake.

Thanks again.

**Comment by Vitaliy-1** [comment]
@anupent 
Also, if we haven't got any XML downloaded as a galley, article landing page will look slightly different with only abstract available. It was done deliberately. You can view this if/else loop here:
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/objects/article_fulltext.tpl
Principally, it is left only to adapt most used plugins to the theme, translations, and, maybe, templates, which I could forget.
