### ISSUE TITLE
Enrich index journal page

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/oldGregg#25]
Consider adding information to the index journal page. Thinking about a carousel for the latest 3 issues:
https://getbootstrap.com/docs/4.0/components/carousel/#with-indicators
Maybe enclose it in the `if` condition to display only in case of issue image cover.
@anupent, what do you think?

**Comment by anupent** [comment]
Yes, with indicators. Great idea. I would love to see it in action.

I think it would be better if a user is able to determine the number of slides with a slight modification of codes.
And, if a user can modify it with less effort to display not the latest n number of issues but n numbers of featured articles from latest issue or latest n numbers of issues.

**Comment by Vitaliy-1** [comment]
For providing a possibility for modifications by a user, I need first to add a menu for the theme to the dashboard. https://github.com/Vitaliy-1/oldGregg/issues/26

**Comment by kwahyu** [comment]
Latest article, carousel and journal summary in index journal are great features.

**Comment by Vitaliy-1** [comment]
@anupent @kwahyu 
These features are already in the master branch. They can be enabled through `website->appearence`

**Comment by anupent** [comment]
I want to add links to the slider and I added following codes (with double asterix removed):
```
{capture name="forCarouselImages"}
        {foreach from=$latestIssues item=issue key=k}
            <div class="carousel-item {if $k == 0}active{/if}">
               {if $issue->getLocalizedCoverImageUrl()}
                **<a href="{url op="view" path=$issue->getBestIssueId()}">**
                    <img src="{$issue->getLocalizedCoverImageUrl()}" class="img-fluid">
                **</a>**
                {else}
                **<a href="{url op="view" path=$issue->getBestIssueId()}">**
                    <img src="{$defaultCoverImageUrl}" class="img-fluid">
                **</a>**
                {/if}
```
I was expecting it to point to something like
``` https://jlmc.edu.np/index.php/JLMC/issue/view/9```

But it took me to ```https://jlmc.edu.np/index.php/JLMC/9``` throwing 404 error.

How should I modify my codes?

**Comment by Vitaliy-1** [comment]
Good idea!

You forgot to specify page: `{url page="issue" op="view" path=$issue->getBestIssueId()}`

**Comment by kwahyu** [comment]
Is it possible to have left sidebar not only on index journal page but also in each sub menus such as About the Journal etc (certainly not in article details)?

@Vitaliy-1

**Comment by Vitaliy-1** [comment]
You need to do special modifications to the code. The sidebar is coded here:
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/pages/indexJournal.tpl#L64-L75
You can, for example, out this part of the code in a separate file, and through include statement add it to any other page. 
I didn't do this, because in modern sites this approach is rarely used (sidebar for several pages). I'm talking about such online journals, like PLoS ONE, JAMA, Elifesciences, BioMed Journals.
