### ISSUE TITLE
Article detail page shows article only in upper half if "Recommend Articles by Author" plugin is activated

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#3]
So far things are good. But, I get contents of article in article detail (landing) page only in upper half of page.
I have attached a printscreen for an explanation:
![image](https://user-images.githubusercontent.com/15881295/34755775-7194492e-f5ee-11e7-9a29-d8a5a69c20a4.png)

**Comment by Vitaliy-1** [comment]
@anupent 
And without most read article by the same author plugin it looks normal?

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
Yes, without the plugin "Recommend Articles by Author", it works fine.
Then we need to find a way to accomodate this section "Recommended articles by same Author" at the end of the article.

**Comment by Vitaliy-1** [comment]
Ok. Will check.

**Comment by Vitaliy-1** [comment]
@anupent,
Support added
