### ISSUE TITLE
Clicking on the article images leads to 404

### ISSUE THREAD

**Issue by zuphilip** [Vitaliy-1/oldGregg#31]
Clicking on the images of the articles e.g. http://ojsdemo.e-medjournal.com/index.php/oldGregg/issue/view/1 leads to 404 error. However, clicking on the title besides works.

**Comment by Vitaliy-1** [comment]
@zuphilip 
Thanks for reporting. Should be fixed with referent patch. Let me know if the problem reoccurs, I will reopen the issue.
