### ISSUE TITLE
##plugins.themes.PMGPTheme.no-affiliation## 

### ISSUE THREAD

**Issue by zuphilip** [Vitaliy-1/oldGregg#32]
If I leave the affiliation field empty then in the published article in the details I see the string `##plugins.themes.PMGPTheme.no-affiliation## ` which is not resolved. Google find others that have the same problem, e.g. https://jlmc.edu.np/index.php/JLMC/article/view/55#nav-details

**Comment by Vitaliy-1** [comment]
Do you use the latest version of the theme?

**Comment by Vitaliy-1** [comment]
@zuphilip 
Let me know if this patch resolves the issue.

**Comment by anupent** [comment]
Yup. resolved.
