### ISSUE TITLE
Some contents of article metadata (abstract) is visible above header

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#34]
Hi @Vitaliy-1 , 
I have problem with maybe five of our articles in that some of the text of metadata (abstract) is visible above header pushing header below. Some articles without XML (abstract only) and one with XML is showing problem.
Here is the screenshot of what I mean:
![image](https://user-images.githubusercontent.com/15881295/35804964-0d9d9bc8-0aa2-11e8-98f2-3cd461cf1a33.png)

Firefox inspector shows few paragraphs and part of closing tag and then ? contents of head in the body as below:
![image](https://user-images.githubusercontent.com/15881295/35805058-789a5dd0-0aa2-11e8-87ed-b27ce44da8c4.png)

There is nothing unusual with the content of abstract:
![image](https://user-images.githubusercontent.com/15881295/35805114-b4e26d32-0aa2-11e8-9f2d-96ed0cf3bfa6.png)

and problem starts from the red mark
![image](https://user-images.githubusercontent.com/15881295/35805150-d8795940-0aa2-11e8-82d2-1e03be1b9cf3.png)
 
I do not have the problem with default theme:
![image](https://user-images.githubusercontent.com/15881295/35805225-1c522188-0aa3-11e8-9053-c7e900d5a0f9.png)

Any idea what is going wrong here?

Best regards,
@anupent

**Comment by Vitaliy-1** [comment]
Hi @anupent 
You should escape HTML special symbols, like `"`(3rd line):
https://www.dvteclipse.com/documentation/svlinter/How_to_use_special_characters_in_XML.3F.html#gsc.tab=0
Tell me if this resolves the problem.

**Comment by anupent** [comment]
Problem solved.

But I am unable to use quotation marks even in codes as &#34;. TinyMCE editor makes permanent quotation marks. I used ' instead.

**Comment by Vitaliy-1** [comment]
@anupent 
You say that all works fine with the default theme?
It's quite possible that `strip_unsafe_html` function, which PKP team uses for managing special symbols in the abstract content, don't work in case of the child theme.

**Comment by Vitaliy-1** [comment]
@anupent 
I cannot reproduce the problem on my local installation. Can you tell me, if you somehow had changed this line in your config:
https://github.com/pkp/ojs/blob/master/config.TEMPLATE.inc.php#L269

**Comment by Vitaliy-1** [comment]
Ahhh,
Another what I see is the modifications in your header. The problem actually arises because of not properly escaping the HTML there. It is either `headeHead.tpl` or a custom plugin. `<meta property="og:description" content="problem is here">`

**Comment by anupent** [comment]
No, allowed html is not changed at all.
"a[href|target|title],em,strong,cite,code,ul,ol,li[class],dl,dt,dd,b,i,u,img[src|alt],sup,sub,br,p" mine
"a[href|target|title],em,strong,cite,code,ul,ol,li[class],dl,dt,dd,b,i,u,img[src|alt],sup,sub,br,p" github

About headerHead.tpl, there was a problem where I got "Open Journal System" and not the title of the article. So I had edited it as below.
```
<meta property="og:description" content="<h1>{$article->getLocalizedTitle()|escape}</h1>{$article->getLocalizedAbstract()|strip_unsafe_html}" />
```

**Comment by Vitaliy-1** [comment]
You should not put <h1> or any other tag inside element's attribute value. You should escape any XML (HTML) special symbol there. Take a look at the Social Plugin mockup:
https://github.com/Vitaliy-1/socialMeta/blob/master/SocialMetaPlugin.inc.php#L36-L62
