### ISSUE TITLE
Main page shows articles from other journals

### ISSUE THREAD

**Issue by zuphilip** [Vitaliy-1/oldGregg#35]
We run one OJS instance with several journals and only one journal currently tests now the oldGregg theme.  But on the main page of this journal, we see now articles from the other journals as well. Is this reproducible?

**Comment by Vitaliy-1** [comment]
The referent patch should fix the issue. Can you apply it (from the line 188) and tell whether the problem resolves?

**Comment by zuphilip** [comment]
@dennmuel Can you try out the new master of oldGregg for our OJS instance?

**Comment by dennmuel** [comment]
@zuphilip , done. Looks right now. Thanks a lot, @Vitaliy-1 !

**Comment by zuphilip** [comment]
Thank you both very much!
