### ISSUE TITLE
Article metadata of the same author switched in article details

### ISSUE THREAD

**Issue by kwahyu** [Vitaliy-1/oldGregg#38]
Dear @Vitaliy-1 
Strange thing happen for article metadata displayed in article details.
Please take a look this http://jurnalbeta.ac.id/index.php/betaJTM/article/view/100. The metadata (title, author, abstract, published time) is different with the title.
So is http://jurnalbeta.ac.id/index.php/betaJTM/article/view/4
The two articles have similar corresponding author. I have checked in article metadata of both articles, it is all fine. I tried using default theme, it does not have any problem with metadata displayed in article detail. So, I assume this relates to oldGregg

**Comment by Vitaliy-1** [comment]
Hi @kwahyu 
Dou you use recommended by author plugin? If so, it produces conflicts.
 See:
https://github.com/Vitaliy-1/oldGregg/issues/18
and 
https://github.com/pkp/pkp-lib/issues/2527
Disabling it removes the problem

**Comment by kwahyu** [comment]
It is resolved for turning the plugin off. Sorry for not read the previous issue carefully
