### ISSUE TITLE
ORCID for Authors

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#39]
Hi @Vitaliy-1 ,
Can you add ORCID of authors in article detail page under Affiliations.

Further, my request is to replace "Affiliations" with "Author Details". What do you say?

![image](https://user-images.githubusercontent.com/15881295/36977759-5afdb222-20aa-11e8-9e55-a54375e28468.png)

Best regards,
@anupent

**Comment by Vitaliy-1** [comment]
OK. If adding ORCID it makes sense to rename to `Author(s) Details`.  I will keep this in mind.

**Comment by anupent** [comment]
This patch will address this issue:
https://github.com/Vitaliy-1/oldGregg/commit/14a9c39903db27f193aa5384b2c33b47e44562cf

closed.
