### ISSUE TITLE
Add support for disqus plugin

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#40]
ajnyga seems to have developed a few plugins among which "disqus" looks promising at the moment.

Here is the discussion thread: https://forum.pkp.sfu.ca/t/a-couple-of-plugins-to-the-plugin-gallery/39134/6

And here is the Github repo: https://github.com/ajnyga/disqus

Right now, as we activate the plugin, we do not get contents of the article in the article landing page.

**Comment by Vitaliy-1** [comment]
It uses `Templates::Article::Footer::PageFooter` hook for displaying a front-end part. As the theme hasn't got any footer on the article landing page, where do you propose to place this hook? Add another tab?

Actually, I already see this hook in the theme here: https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/parser/articleMainText.tpl#L243
So it should work.

**Comment by Vitaliy-1** [comment]
Under details tab

**Comment by Vitaliy-1** [comment]
Hi @anupent 
So, can you describe more precisely what is not happening from what you expect? 
If the plugin isn't working, is there something in the error log?
Is plugin working with the default theme? If yes, can you play around with the hook placing it somewhere else in the template?

**Comment by varshilmehta** [comment]
It only works when it is placed in the beginning or something which is active right when you enter the page, It won't work when you place in tabs or any other place.
