### ISSUE TITLE
Adding navbar-fixed-top

### ISSUE THREAD

**Issue by kwahyu** [Vitaliy-1/oldGregg#41]
Dear @Vitaliy-1 
Is it possible to add fixed-top for navbar? 
I read this https://getbootstrap.com/docs/3.3/components/#navbar-fixed-top but cannot find the proper place to customize

**Comment by Vitaliy-1** [comment]
Are you sure that Element's class migrated to Bootstrap 4?  Keep in mind that this theme uses the latest Bootstrap version. Also, as I remember that could be achieved by simply adding `position: sticky;` in CSS. 

The primary and secondary menu a situated here: https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/components/header.tpl#L19-L90

**Comment by kwahyu** [comment]
I am not sure. I will try with CSS
Thanks @Vitaliy-1

**Comment by Vitaliy-1** [comment]
@kwahyu 
How it goes? Can I close this issue?

**Comment by kwahyu** [comment]
Sorry, I don't think it is a good option after trying.
