### ISSUE TITLE
Error 500 after installing

### ISSUE THREAD

**Issue by lukazsj** [Vitaliy-1/oldGregg#42]
I tried to install both, master and 1.1.0.0, but it threw this expection in apache log:
 PHP Fatal error:  Call to undefined method OldGreggThemePlugin::addMenuArea() in /home/www/ojs/plugins/themes/oldGregg/OldGreggThemePlugin.inc.php on line 75

I'm using OJS 3.0.2.

**Comment by Vitaliy-1** [comment]
Hi @lukazsj 
Unfortunately, none of the plugin's versions supports OJS 3.0.2. 
Custom menu areas are supported from OJS 3.1, so you can expect that the theme will work after the upgrade to this or more recent OJS version.
