### ISSUE TITLE
Add logo/banner in the header

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#5]
Name of the journal in the header comes from "Journal Name" in journal settings.
I did not find a way to add logo or banner. It would be reasonable to add them.

**Comment by Vitaliy-1** [comment]
It can be done. But we cannot put a logo more than space in the header.

**Comment by Vitaliy-1** [comment]
@anupent 
Have added necessary code. Max logo height is 60px. Do you have any ideas, how we can style logo area better?

**Comment by anupent** [comment]
I don't have problem with the format of default or manuscript theme. 
In the current theme, though search area looks good, it occupies a row of space. We can preserve this space by moving search area to the current logo position and place a bigger logo above the menu items.

**Comment by Vitaliy-1** [comment]
I am thinking about adding a `div` element for logo between 2 menus in the header. This `div` will be displayed in case if the user actually uses a logo.

**Comment by anupent** [comment]
sounds great.

**Comment by Vitaliy-1** [comment]
Hi @anupent 
In this 2 patches, I have added a logo inside header as an additional `div`.
it will be displayed on all pages, except article landing page.
What do you think about this?

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
Much better. And now this theme appear to be as if ready for production use. (Though i have bee using it for a few days now)
I would modify it in my case by moving the search box and button to the right side of main nav thus further decreasing the Header height.

**Comment by Vitaliy-1** [comment]
@anupent 
In case of your proposal, the header would be just like that on Bootstrap site: 
https://getbootstrap.com/docs/4.0/components/navbar/#supported-content
But I want something different :)

You can do it by yourself from the child theme. It would be something like:

```
<form class="form-inline my-2 my-lg-0" action="{url page="search" op="search"}" method="post" role="search">
      <input class="form-control mr-sm-2" type="text" value="{$searchQuery|escape}"  aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{translate key="plugins.gregg.search"}</button>
</form>
```
Place these lines here: https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/components/header.tpl#L65

You'll need to remove the journal title from the article page in this case (for a better look): 
https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/components/header.tpl#L67-L69

You can open a new issue if there would be any problems with this.
