### ISSUE TITLE
Editorial Team and Archive Page not displayed

### ISSUE THREAD

**Issue by niazpur** [Vitaliy-1/oldGregg#50]
I installed bootstrap 4 themes today and facing two issues:
1- Editorial team page does not show board members details although these are there in Settings > Journal MASTHEAD.

2- Archive link in the menu when clicked shows a blank page.

Looking forward to your solution, please.
Nadeem

**Comment by Vitaliy-1** [comment]
Hi @niazpur 
What OJS version you are using?

**Comment by niazpur** [comment]
The latest one , I updated today to 3.1.1.1 and then installed bootstrap theme on it for the first time.

**Comment by niazpur** [comment]
Sorry forgot to mention my journal link:
https://journal.seisense.com/index.php/jom

I customized the editorial page by giving the custom link in the menu so it is displaying but the default link of editorial team in masthead does not display.

**Comment by Vitaliy-1** [comment]
@niazpur 
The theme is not adapted to work with OJS 3.1.1. I am planning to finish the work on this tomorrow.

**Comment by niazpur** [comment]
So, you mean I should expect the update on it by tomorrow. Thats great.

**Comment by niazpur** [comment]
Although, I have purchased version of OJS theme, but I am in love of your theme. It is so much elegant that I have already installed OJS 3.1.0-1 and using your theme.
You did Wonderfull job.!
Thanks

**Comment by Vitaliy-1** [comment]
Master branch is now in compliance with OJS 3.1.1
