### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#52]
Hello, there are some points that need translations. 
How can I translate Latest Issues `##Plugins.Gregg.Issues.Slider.Title##` in Spanish?... 

Thanks

**Comment by Vitaliy-1** [comment]
In English it is: `latest issues`

**Comment by Vitaliy-1** [comment]
You should put this line: https://github.com/Vitaliy-1/oldGregg/blob/master/locale/en_US/locale.xml#L53
into this file: https://github.com/Vitaliy-1/oldGregg/blob/master/locale/es_ES/locale.xml
and change the content of the translation into Spanish

**Comment by josuevalrob** [comment]
I have this in english: 1-25 of 129 Next
In spanish: ##common.pagination## Siguiente

How can I translate or in this case, not translate that?
