### ISSUE TITLE
activate plugin on index site 

### ISSUE THREAD

**Issue by cristiaan3003** [Vitaliy-1/oldGregg#54]
When activate plugin in index site (/index.php/index - multi-journal installation) not show lenguaje block plugin on the right. I check my configuration block "Sidebar management" -> Language Toggle Block  is active. How can i fix this

**Comment by Vitaliy-1** [comment]
To work properly on multi-journal installations theme needs some readjustments. I'm right now on a trip and will return to this maybe in the next week.

**Comment by vvelma** [comment]
What are the adjustments that must be made to apply the oldGregg theme to the multi-journal site? Installation ojs 3.1.2

**Comment by Vitaliy-1** [comment]
Will be implemented in the next release
