### ISSUE TITLE
show email address of corresponding author

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#56]
I believe email id of corresponding author is not visible now under "details" tab.
Adding this feature would be useful.

**Comment by kwahyu** [comment]
Same idea as @anupent

**Comment by anupent** [comment]
I can fetch author email by using code {$author->getEmail()}. But this will fetch email for all authors in the loop for authors.

I want to fetch email only for corresponding author. What codes should I use to check if the author is a corresponding author?

**Comment by anupent** [comment]
@Vitaliy-1,
See this pull request.
https://github.com/Vitaliy-1/oldGregg/pull/57

**Comment by anupent** [comment]
https://github.com/Vitaliy-1/oldGregg/commit/c2fbfbe948de5f789e478acdb8e5681d936508d4
