### ISSUE TITLE
Consider to shrink menu height on an article landing page

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/oldGregg#6]
Quite reasonable in present hight it can distract users from reading the article. A javascript mechanism for reducing height while reading should be considered.

**Comment by anupent** [comment]
A temporary solution:
I edited article.tpl and removed logo, moved user nav to main nav.
![image](https://user-images.githubusercontent.com/15881295/34981243-0ae10b00-facf-11e7-84b8-ef4c4b27decf.png)
