### ISSUE TITLE
request from the user to agree to the terms of the privacy policy

### ISSUE THREAD

**Issue by sbirAECA** [Vitaliy-1/oldGregg#61]
Good morning Vitaliy
My name is Carlos from Spain.
First I want to thank you for all this oldGregg theme. It is really an excelent job
I am involved into the process of migrating from ojs2 to ojs3 and I am testing your theme.
With the new version OJS 3.1.1-1 there is a commit from lib/pkp including a request from the user to agree to the terms of the privacy policy, and this is affecting to your userRegister.tpl (https://github.com/pkp/pkp-lib/issues/3575)

Here is the the code:

>             <fieldset class="consent">
>                 {* Require the user to agree to the terms of the privacy policy *}
>                 <div class="fields">
>                     <div class="optin optin-privacy">
>                         <label>
>                             <input type="checkbox" name="privacyConsent" value="1"{if $privacyConsent} checked="checked"{/if}>
>                             {capture assign="privacyUrl"}{url router=$smarty.const.ROUTE_PAGE page="about" op="privacy"}{/capture}
>                             {translate key="user.register.form.privacyConsent" privacyUrl=$privacyUrl}
>                         </label>
>                     </div>
>                 </div>
>                 {* Ask the user to opt into public email notifications *}
>                 <div class="fields">
>                     <div class="optin optin-email">
>                         <label>
>                             <input type="checkbox" name="emailConsent" value="1"{if $emailConsent} checked="checked"{/if}>
>                             {translate key="user.register.form.emailConsent"}
>                         </label>
>                     </div>
>                 </div>
>             </fieldset>

Best regards
Carlos 

PS
I saw with OJS3 when rendering the reference list there are two options:
  1 taking the whole list (it is recorded into citation field of the submissions table)
  2 taking the parsered list and every record can be rendered with a link (citations table)

this is the code at templates/frontend/objects/article_details.tpl

> 			{* References *}
> 			{if $parsedCitations->getCount() || $article->getCitations()}
> 				<div class="item references">
> 					<h3 class="label">
> 						{translate key="submission.citations"}
> 					</h3>
> 					<div class="value">
> 						{if $parsedCitations->getCount()}
> 							{iterate from=parsedCitations item=parsedCitation}
> 								<p>{$parsedCitation->getCitationWithLinks()|strip_unsafe_html} {call_hook name="Templates::Article::Details::Reference" citation=$parsedCitation}</p>
> 							{/iterate}
> 						{elseif $article->getCitations()}
> 							{$article->getCitations()|nl2br}
> 						{/if}
> 					</div>
> 				</div>
> 			{/if}

**Comment by mo574216** [comment]
Hi,
I have encountered the same issue on my website. Is there any schedule to fix it?

**Comment by Vitaliy-1** [comment]
Does this solve a problem: https://github.com/Vitaliy-1/oldGregg/commit/e312acd2f988ade35914cecbf18d669b9137d4e9

**Comment by anupent** [comment]
@Vitaliy-1 , it solves. 
However, no ideas about the references. Does it matter to those who used this theme?

**Comment by Vitaliy-1** [comment]
Right now those references will be shown if JATS XML doesn't have own reference block.

**Comment by anupent** [comment]
For eg, if we have only abstract (where references won't be shown from XML), will references be visible using this theme with this modification in articleOnlyAbstract.tpl?

**Comment by sbirAECA** [comment]
sorry ... aren't incluiding the 'ref-list' at the 'back' in xml-jats

**Comment by sbirAECA** [comment]
You can see at http://sbir.upct.es:8080/index.php/sbir/article/view/20

**Comment by sbirAECA** [comment]
diff --git a/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl b/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
index 2da3bae..3bea8bf 100755
--- a/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
+++ b/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
@@ -46,16 +46,20 @@
         </nav>
         <div class="tab-content" id="nav-tabContent">
             <div class="tab-pane fade" id="nav-references" role="tabpanel" aria-labelledby="nav-references-tab">
-                {* References *}
-                {if $article->getCitations()}
-                    <div class="references">
-                        <div class="value">
-                            {if $article->getCitations()}
-                                {$article->getCitations()|nl2br}
-                            {/if}
-                        </div>
-                    </div>
-                {/if}
+				{* References *}
+				{if $parsedCitations->getCount() || $article->getCitations()}
+					<div class="references">
+						<div class="value">
+							{if $parsedCitations->getCount()}
+								{iterate from=parsedCitations item=parsedCitation}
+									<p>{$parsedCitation->getCitationWithLinks()|strip_unsafe_html} {call_hook name="Templates::Article::Details::Reference" citation=$parsedCitation}</p>
+								{/iterate}
+							{elseif $article->getCitations()}
+								{$article->getCitations()|nl2br}
+							{/if}
+						</div>
+					</div>
+				{/if}				
             </div>
             <div class="tab-pane fade show active" id="nav-download" role="tabpanel" aria-labelledby="nav-download-tab">
                 {if $primaryGalleys}

**Comment by sbirAECA** [comment]
Here you have the articleOnlyAbstract.tpl.diff

```
diff --git a/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl b/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
index 2da3bae..3bea8bf 100755
--- a/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
+++ b/plugins/themes/oldGregg/templates/frontend/objects/articleOnlyAbstract.tpl
@@ -46,16 +46,20 @@
         </nav>
         <div class="tab-content" id="nav-tabContent">
             <div class="tab-pane fade" id="nav-references" role="tabpanel" aria-labelledby="nav-references-tab">
-                {* References *}
-                {if $article->getCitations()}
-                    <div class="references">
-                        <div class="value">
-                            {if $article->getCitations()}
-                                {$article->getCitations()|nl2br}
-                            {/if}
-                        </div>
-                    </div>
-                {/if}
+				{* References *}
+				{if $parsedCitations->getCount() || $article->getCitations()}
+					<div class="references">
+						<div class="value">
+							{if $parsedCitations->getCount()}
+								{iterate from=parsedCitations item=parsedCitation}
+									<p>{$parsedCitation->getCitationWithLinks()|strip_unsafe_html} {call_hook name="Templates::Article::Details::Reference" citation=$parsedCitation}</p>
+								{/iterate}
+							{elseif $article->getCitations()}
+								{$article->getCitations()|nl2br}
+							{/if}
+						</div>
+					</div>
+				{/if}				
             </div>
             <div class="tab-pane fade show active" id="nav-download" role="tabpanel" aria-labelledby="nav-download-tab">
                 {if $primaryGalleys}
```
