### ISSUE TITLE
Article figures and default issue image not loading

### ISSUE THREAD

**Issue by B5045438** [Vitaliy-1/oldGregg#63]
The default issue image and images of figure are not appearing on the site. The default issue image is returning 404 and the figure don't seem to throw any codes but just refuse to load. Tested with the JATS XML articles provided with the docx2jats converter:  https://github.com/Vitaliy-1/DOCX2JATS

**Comment by Vitaliy-1** [comment]
Can you check the permissions for default issue image? 
As for figures, I need more info:
1. How do they look like inside JATS XML (`fig` node with child nodes)?
2. How are they uploaded to the site?
3. What application you are using (OJS? and what version)?

**Comment by B5045438** [comment]
All permissions seem to be enabled for the default issue image when I checked it using ls -alt in my Linux terminal.

1- For the figures here an example:
`<fig id="fig1">
            <object-id pub-id-type="doi"/>
            <label>The project aim is to create a computational model of the biological dynamics, generating the basic architecture of the human retina in a biologically plausible way using BioDynaMo</label>
            <caption>
               <title>The main focus will be on the development of the five major retinal layers outer nuclear layer (ONL), outer plexiform layer (OPL), inner nuclear layer (INL), inner plexiform layer (IPL) and ganglion cell layer (GCL) (<xref ref-type="fig" rid="fig1">Figure 1</xref>).</title>
            </caption>
            <graphic xlink:href="https://e-medjournal.com/suppl/"/>
</fig>`

2- So far I just assumed the xml would sort out images on its own, so I assume this is probably the issue. Where do I upload the images and how do I link them to the xml?

3- OJS 3.1.1

**Comment by Vitaliy-1** [comment]
You should put here: `xlink:href="https://e-medjournal.com/suppl/"/` an actual image file name with extension. For example, `fig1.jpg`. And attach the image with this name to the XML galley.   
![attachtoxml](https://user-images.githubusercontent.com/20665587/41660461-c63ba424-74a4-11e8-9ed5-3aea4ef58c5d.jpg)

**Comment by B5045438** [comment]
Do I upload it in a seperate Galley? Because anything I upload to the same Galley replaces the original file.

**Comment by Vitaliy-1** [comment]
No. Press the edit button under XML galley.

**Comment by B5045438** [comment]
![image](https://user-images.githubusercontent.com/40169297/41667287-7abb3334-74a4-11e8-9784-ba29a5cb918a.png)

Can't seem to find the option for some reason.

**Comment by B5045438** [comment]
I have full access to the database, I had the same issue with the modified xml manuscript theme.

**Comment by Vitaliy-1** [comment]
Can you check the `file_type` of your uploaded XML file inside `submission_files` table?
Is it `application/xml` or `text/xml`?

**Comment by B5045438** [comment]
It's been uploaded as a text_xml it seems.

**Comment by B5045438** [comment]
Yeah that fixed the issue, I now I can upload additional files to the galley. About the default issue image, is it expecting ojs to be the root of the site? If so how can I change the url it is trying to access.

**Comment by B5045438** [comment]
Just tried to upload an image as fig1.jpg to the xml galley, but I'm getting a 404 not found. Could this be also related to the web roots possibly not matching? It is trying to access:

/ojs/index.php/student/article/view/3/fig1.jpg

I'm not completely familiar with where ojs store the images, so I can't figure out where to look for the image in the site resources.

**Comment by josuevalrob** [comment]
Changing that line in the articleGalleryForm.tpl solve the problem. It works perfectly now. 

Inspecting the element I found that the image is store in /old_gregg/index.php/ingenieria-civil/article/download/1279/1270/1783. 
But, @B5045438  you dont need to put that adress in the XML file, just: 

` **xlink:href="image6.jpeg"**`

**Comment by B5045438** [comment]
@josuevalrob @Vitaliy-1 I did as you shown, I placed fig.jpg. That's the address the broswer tried to access but got a 404 from, I suspect it might be caused by it not matching the web root and I need to verify if the path is correct.

**Comment by diegomejia071** [comment]
Hi,

I am using OJS version 3.1.2.0, and the lens article viewer. But when I upload the images to it, he saves them to me in the delivery, but they are not displayed in the lens viewfinder. I get a 404 error.

Regards…
