### ISSUE TITLE
Show Author biography from Metatags

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#65]
Hello, this is a feature request. 

I want to include the biography of authos from articles without the xml view. 
For example this one: 
[article](http://5.56.56.37/old_gregg/index.php/ingenieria-civil/article/view/1294)

Looking into the code, it has to be something in [articleOnlyAbstract.tpl in the line 123](https://github.com/Vitaliy-1/oldGregg/blob/master/templates/frontend/objects/articleOnlyAbstract.tpl#L123)

And looking into the article_details.tpl from OJS I found that they call the Author Biography with this: 

```
{$author->getLocalizedBiography()|strip_unsafe_html} 
```

But, for some reason, it print me a <p> and a &nbdsp

> &lt;p&gt;&amp;nbsp;&lt;/p&gt;&nbsp;asdasdasdasdaasdasdasd                                    

And If I follow the same way that you call the afilation I got this: 
```
<p>{if $author->getLocalizedBiography()}{$author->getLocalizedBiography()|escape}{else}{translate key="plugins.gregg.no-affiliation"}{/if}</p> 
```
And the result is pretty weird: 

> &lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;div id="selenium-highlight"&gt;&amp;nbsp;asdasdasdasdaasdasdasd&lt;/div&gt;

It can be fixed withn some css or js, but I think it could be a good functionality. thanks

**Comment by Vitaliy-1** [comment]
Yep, Author Biography is a good idea. I'll consider adding it as a Bootstrap's modal for future Old Gregg release.
