### ISSUE TITLE
Login page is broke. 

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#67]
After import my site to the production, everythin works fine, except the login page. 

![image](https://user-images.githubusercontent.com/10994342/42088563-2cd15c8c-7b9a-11e8-85a7-ca8b02dc7e0c.png)

The console is fine. 

The header is doing this: 
![image](https://user-images.githubusercontent.com/10994342/42088614-642dbd60-7b9a-11e8-9c82-7ff7ebe33838.png)

Can you check the site [here](http://5.56.56.37/CEDEX/index.php/ingenieria-civil/login)

**Comment by Vitaliy-1** [comment]
It seems that that template comes from the other (possibly default) theme. Can you clear the template cache?

**Comment by josuevalrob** [comment]
Yeah, fixed
