### ISSUE TITLE
Error on archive page

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#69]
This is the error

`Fatal error: Uncaught Error: Call to undefined method IssueDAO::getShowTitle() in /var/www/html/jmp/cache/t_compile/6267f877acd9b945f8a07db7bb24329a969a952a^%%91^91C^91C532D2%%issue_summary.tpl.php:5 Stack trace: #0 /var/www/html/jmp/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include() #1 /var/www/html/jmp/lib/pkp/classes/template/PKPTemplateManager.inc.php(416): Smarty->_smarty_include(Array) #2 /var/www/html/jmp/cache/t_compile/f66927e784c208f8ece0b3df96fabeb6da725ad3^%%6B^6B5^6B5271FB%%issueArchive.tpl.php(39): PKPTemplateManager->_smarty_include(Array) #3 /var/www/html/jmp/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1257): include('/var/www/html/j...') #4 /var/www/html/jmp/lib/pkp/classes/template/PKPTemplateManager.inc.php(793): Smarty->fetch('frontend/pages/...', NULL, 'f66927e784c208f...', true) #5 /var/www/html/jmp/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1107): PKPTemplateManager->fetch('frontend/pages/...', NULL, 'f66927e784c208f...', true) #6 /var/www/html/jmp/lib/pkp in /var/www/html/jmp/cache/t_compile/6267f877acd9b945f8a07db7bb24329a969a952a^%%91^91C^91C532D2%%issue_summary.tpl.php on line 5`

**Comment by Vitaliy-1** [comment]
And what OJS version you are using?

**Comment by varshilmehta** [comment]
3.1.0.1

**Comment by Vitaliy-1** [comment]
The error should resolve from OJS version 3.1.1+

**Comment by varshilmehta** [comment]
Thanks. It worked.
