### ISSUE TITLE
Add possibility to change number of latest articles

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/oldGregg#7]
Currently, 20 latest articles are displayed on journal index page. It should be considered a mechanism that would give to the user the control of articles number to be displayed.

**Comment by anupent** [comment]
Hi @Vitaliy-1 ,
I tried to introduce a {break} if number of articles exceed 12, but could not execute. Can you see what should I have done to make it work. I have marked the codes I added with a red tick.

![image](https://user-images.githubusercontent.com/15881295/35476940-62830b90-03e1-11e8-864d-b940f8f9df27.png)

**Comment by Vitaliy-1** [comment]
@anupent 

You can look here for incrementing the value to an assigned inside Smarty variable: https://stackoverflow.com/questions/8674831/how-do-you-increment-an-assigned-variable-in-smarty-without-displaying-it
But as I remember, you can use $k variable (key of an associative array) for this task. Just enclose all under `foreach` loop with:
```
{if $k<12}
  <div class="recent-wrapper">
  ....
  </div>
{/if}
```

**Comment by Vitaliy-1** [comment]
I am now in a free time working on a rewriting JATS Parser Plugin. Making a foundation for online JATS XML Editor for Old Gregg theme. So, wouldn't be able to add user-friendly control on such theme variables in near time.

**Comment by anupent** [comment]
It worked. Thanks.

**Comment by Vitaliy-1** [comment]
@anupent 
I have added the possibility to change the number of latest articles on the journal index page. You can find it at: dashboard -> website settings -> appearance; 
just under the theme changer.
