### ISSUE TITLE
New Error in only one article in OJS 3.1.1.2

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#70]
Fatal error: Uncaught TypeError: Return value of JATSParser\Body\Section::getTitle() must be of the type string, null returned in /home/u796555399/public_html/plugins/themes/oldGregg/jatsParser/src/JATSParser/Body/Section.inc.php:36 Stack trace: #0 /home/u796555399/public_html/cache/t_compile/6267f877acd9b945f8a07db7bb24329a969a952a^%%A2^A2D^A2DEEC56%%articleMainText.tpl.php(46): JATSParser\Body\Section->getTitle() #1 /home/u796555399/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870):

**Comment by Vitaliy-1** [comment]
This means that you've missed a title inside one of the sections. You can change return type here: https://github.com/Vitaliy-1/oldGregg/blob/master/jatsParser/src/JATSParser/Body/Section.inc.php#L35
from `string` to `?string` (null or string).

**Comment by varshilmehta** [comment]
Correct. This inbuilt Jatsparser is kind of more strict than your previous independent version.
