### ISSUE TITLE
Feature request: popup for reference display in text

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#71]
Is there any way to start the popup feature again in the text? Also Most read articles feature is the need of the day? Is that possible as well?

**Comment by Vitaliy-1** [comment]
It's possible and I am considering to add this in the future. The easiest way is to add some javascript code for Bootstrap's popovers: https://getbootstrap.com/docs/4.1/components/popovers/

**Comment by varshilmehta** [comment]
OKay, what should I put in data-content="???"

**Comment by Vitaliy-1** [comment]
I'd not recommend to anything here because in the new release is planned many modifications of article landing page template. It would have a newspaper style, something similar to Elifesciences journal. style.

**Comment by Vitaliy-1** [comment]
JATS Parser plugin v.2 not ready yet, but: http://dev-ojs.e-medjournal.com/index.php/sjt/article/view/13/26
Is planned to be integrated into new OJS themes.

**Comment by varshilmehta** [comment]
What an awesome work. Can I start working on it as well for my own child
theme pls?
Regards,
Dr. Varshil Mehta, MBBS

Dept. of Internal Medicine, Seven Hills Hospital, Mumbai | Medical
Graduate, MGM Medical College, Navi Mumbai | Founder & CEO, JMRI
Publications, Mumbai | Editor in Chief, Journal of Medical Research and
Innovation | Managing Editor, JMRI Open | Editor, Journal of Insulin
Resistance | Editor, Cureus | Collaborator, Global Burden Disease

**Comment by Vitaliy-1** [comment]
Are you talking about a new theme or a plugin? The plugin renders only XML article galley page and produces PDF.

**Comment by varshilmehta** [comment]
Both. Currently I am running OldGregg. What can I use?

**Comment by Vitaliy-1** [comment]
The theme is planned for a release soon (maybe a week or so). The plugin slightly later.

**Comment by varshilmehta** [comment]
Check this layout: Its plain and simple. https://www.oatext.com/awareness-without-explicit-recall-features-and-research-perspective.php#Article

**Comment by Vitaliy-1** [comment]
I've already picked up a layout. It would be similar to XML Galley page of the JATS Parser Plugin. It is clean and quite unique. And it's better in terms of support (2 different layouts are harder to support than 1).
