### ISSUE TITLE
How to show video files?

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#73]
In manuscript theme, I was able to show them up. But now its not working in this theme. Any ideas?

**Comment by Vitaliy-1** [comment]
It's implemented only in the future release

**Comment by varshilmehta** [comment]
Umm okay. I have already published video articles before. I am not sure what to do now with them.
Also if I dont want to show one section of articles on the front page, what should I do?

**Comment by Vitaliy-1** [comment]
You can copy a code for the new release (but it would require some coding skills). Introducing new Class for external video: https://github.com/Vitaliy-1/JATSParser/blob/036d90d1ca4c1fa79b4ebd444bdcb20eab6382eb/src/JATSParser/Body/Document.php#L140-143
https://github.com/Vitaliy-1/JATSParser/blob/036d90d1ca4c1fa79b4ebd444bdcb20eab6382eb/src/JATSParser/Body/Media.php
The realization by the Smarty templates, basically is the same as for tables/figures.

**Comment by varshilmehta** [comment]
I did try, but it didnt work. Got an error. I will have to wait until you update this theme i guess.
