### ISSUE TITLE
oldGregg (Theme for OJS 3)

### ISSUE THREAD

**Issue by fikretylmaz** [Vitaliy-1/oldGregg#74]
Hello M.D. Proffesor,
I am a proffesor teaching music at Tokat Gaziosmanpaşa University in Turkey Also manager of Rast Musicology Journal. I tried to install your oldGregg thema but it looks like that blow. May i get any help? email: fikrisoysall@gmail.com
![image](https://user-images.githubusercontent.com/41520387/43040195-732e0154-8d46-11e8-9cd2-20cc65c4bcc1.png)

**Comment by josuevalrob** [comment]
If you inspect the element(F12) and looks for the console errors, all the problems are for missing files, like css, js or images. 
Here are some tips:
1) Try to delete cache
2) Check if the Oldgregg theme has the correct name. 
3) Track the console erros, this will give you a clue about where is it searching the elements (css, js, images). 

For more help, print the console error.

**Comment by fikretylmaz** [comment]
Thank you very much its done working. Great job!
