### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by fikretylmaz** [Vitaliy-1/oldGregg#77]
Hello,
Finally I set oldGregg theme that its great job. How could I add my articles as shown below. Can you explain in order to be done? Thank you very much.
![image](https://user-images.githubusercontent.com/41520387/43086581-611a49d0-8ea6-11e8-8ff2-7cf810c4d04a.png)

**Comment by josuevalrob** [comment]
You need the XML file in a JATS format. 

Here is an [example ](https://github.com/Vitaliy-1/DOCX2JATS/blob/master/article1.xml)of it. You can download it and try to upload it. 

The process to upload the file is with galleries, you just need to go into the production stage and add a new one. 

For the images, automatically, after OJS detect that it is a new XML file, it will give you the option to upload them, just go to edit the gallery and at the button, it will appear.

**Comment by fikretylmaz** [comment]
Thank you for help but I could not do that :( do you have any video tutorial?

**Comment by Vitaliy-1** [comment]
Unfortainly, there is no an easy way to do this. I am planning to add DOCX to JATS XML transformation feature to a JATS Parser plugin this autumn.

**Comment by fikretylmaz** [comment]
I tried and succeed almost. 
![image](https://user-images.githubusercontent.com/41520387/43166669-d2d21180-8f9f-11e8-8397-8146cf86ceb4.png)

**Comment by fikretylmaz** [comment]
I did my best from now. except references and details 
![image](https://user-images.githubusercontent.com/41520387/43175178-86576388-8fc6-11e8-9886-2511a1de2664.png)
![image](https://user-images.githubusercontent.com/41520387/43175208-ab871338-8fc6-11e8-911f-7f1d1959d547.png)
