### ISSUE TITLE
UsageStatistics in "Article full text"

### ISSUE THREAD

**Issue by anupent** [Vitaliy-1/oldGregg#8]
Right now, we cannot see "usage statistics" info in the "article full text" page. Can we add a tab in the right side-bar named "Statistics" or anything suitable as shown in figure below.
In this figure, i have reduced the width of right side-bar and increased width of article text area.
![image](https://user-images.githubusercontent.com/15881295/34789528-b77973a6-f666-11e7-8d6e-302a8f45218c.png)

**Comment by anupent** [comment]
I think I have done it. 
![image](https://user-images.githubusercontent.com/15881295/34792728-137286c0-f671-11e7-90fe-ce3af9dfbaea.png)

I have never used Github except for downloading codes. 
I think I should learn how to work in Github.

**Comment by Vitaliy-1** [comment]
Were those views coded without adding getViews() method inside OJS core?

**Comment by anupent** [comment]
No, I used following codes:
`<span>{translate key="article.abstract"} viewed</span> - <b>{$article->getViews()}</b> times.&nbsp <br />
{if is_a($article, 'PublishedArticle')}{assign var=galleys value=$article->getGalleys()}{/if}
{if $galleys}
	{foreach from=$galleys item=galley name=galleyList}
	<span>{$galley->getGalleyLabel()} downloaded</span> - <b>{$galley->getViews()}</b> times.<br />
	{/foreach}
{/if}`

**Comment by Vitaliy-1** [comment]
Can you make a pull request in master branch for such changes:
1. Adding a tab for statistics (suppose, with awesome icon).
2. Adding display for abstract views and pdf downloads (without HTML views).
?

**Comment by anupent** [comment]
Will try. 
I have never used Github except for downloading codes.

**Comment by Vitaliy-1** [comment]
1. Fork master branch (it will appear on your GitHub page).
2. Make necessary changes (in own forked branch)
3. Make a pull request (from own forked code, there will be an option).

**Comment by Vitaliy-1** [comment]
Anyway, I will review the code at this weekend.

**Comment by anupent** [comment]
OJS 3.1.1 and oldGregg theme.
I lost my usageStatistics graphs.

![image](https://user-images.githubusercontent.com/15881295/38546399-43cb2bf0-3ccc-11e8-83a9-956a004d4e5d.png)

I think I have the necessary files too:
![image](https://user-images.githubusercontent.com/15881295/38546621-d5a44156-3ccc-11e8-95bb-3457182210b1.png)

Any idea what is wrong with the statistics graph?

Best regards,

**Comment by anupent** [comment]
Here is the fix:
https://github.com/pkp/pkp-lib/pull/3559/files
