### ISSUE TITLE
how do i change those ##names## 

### ISSUE THREAD

**Issue by fmgermano** [Vitaliy-1/oldGregg#81]
Sorry by the newb question but i just installed the theme but i can't find where to customize those names who appears in this ##form## like where i want to put search it appears something like  "##plugins.gregg.search##" and i tried to change it to "search"on the frontend/header code, it changed but it appeared like "##search##" (those hashtags were still on )

**Comment by Vitaliy-1** [comment]
You can look at English locale as a most full: https://github.com/Vitaliy-1/oldGregg/blob/master/locale/en_US/locale.xml
Just add dir with your locale and add the same tags in your locale.xml for your language. Let me know if you encounter with problems here

**Comment by fmgermano** [comment]
Oh my friend thank you very much i did it !! 
now next challenge is to submite my articles but working on it...reading the forum is really helping me out
Thank you again, i'm so happy to use your theme
