### ISSUE TITLE
Crossmark button

### ISSUE THREAD

**Issue by fikretylmaz** [Vitaliy-1/oldGregg#83]
Dear Prof. Vitaliy
How can I Apply the Crossmark button to oldGregg HTML pages?

<script src="https://crossmark-cdn.crossref.org/widget/v2.0/widget.js"></script>
 <a data-target="crossmark"><img src="https://crossmark-cdn.crossref.org/widget/v2.0/logos/CROSSMARK_BW_horizontal.svg" width="150" /></a>

**Comment by Vitaliy-1** [comment]
You can add javascript directly into the theme, like: https://github.com/Vitaliy-1/oldGregg/blob/master/OldGreggThemePlugin.inc.php#L71
But I'd recommend using a child theme or a plugin for that (Custom Header Plugin)
