### ISSUE TITLE
Show 24 issues in the issues page

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#86]
Hello, How can I show 24 issues in the issue page?.

Cheking the code from issueArchive.tpl the $issues variable comes with 25 elements. 

I was looking where it is declare or how does it ask 25 elements and try to ask just 24, but with not luck. 

The best aproach is in the IssueHanlder.inc.php from the OJS api, but nothing is one there...

Any idea how can I achive that?

**Comment by josuevalrob** [comment]
/management/settings/website
at the end... 
**List elements**

**Comment by Vitaliy-1** [comment]
@josuevalrob Yep, that's general rule for all themes. Keep in mind that it applies to several elements, for example, for authors list on rarely used search authors page: https://e-medjournal.com/index.php/psp/search/authors
