### ISSUE TITLE
Issue Slider Empty. 

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#89]
Hello. 

I don't know why my issue slider from the index journal is empty. 

After synchronization from the repository, it disappeared. 

I didn't touch the code... what could it be?

**Comment by josuevalrob** [comment]
I checked the $lastedIssues variable from issue_slider.tpl and say: 
`{$latestIssues|@var_dump}
`
NULL

**Comment by josuevalrob** [comment]
El plugin está activado

**Comment by josuevalrob** [comment]
Okey, is solved. In the admin page I can modify that, I didnt see it cuz is not translated into spanish, but I already update the locale folder for spanish, so, problem solved!

Thanks!

**Comment by Vitaliy-1** [comment]
Great that you have managed the problem!
