### ISSUE TITLE
target tag

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#91]
Hello. 
Sorry for asking for so many things.. but I am using a lot your theme [DevSite](http://5.56.56.37/CEDEX/index.php/ingenieria-civil)

I want to include internal links on my article. 
So for example this tag: 
`  <p>El <xref ref-type="bibr" rid="CIT80">Pourret, 1796</xref>proyecto comprende el diseño y construcción de  2,2 kilómetros de puente atirantado y viaductos de acceso, de hormigón in situ, así como 9,3 kilómetros de autovía y sus correspondientes enlaces.</p>
`
most be linked with something like this: 
 ` <p><target id="CIT80" >Secciones </target> 1 – ocho existentes: Carreteras asociadas y conexión con enlaces existentes.</p>
`
But the target element doesnt appear on my render file. 

It is coming in the $jatsDocument array?

**Comment by josuevalrob** [comment]
Just in case that someone find the same issue: in the `parser/text.tpl` is the solution:

**Comment by josuevalrob** [comment]
jeje, okey it was simple after all... sorry for texting so much... 

just added the target element into the `$nodecheck`


`	private static $nodeCheck = array("bold", "italic", "sup", "sub", "xref", "underline", "monospace", "ext-link", "target");`

**Comment by Vitaliy-1** [comment]
If the node is inside `p` tag and you don't want to retrieve any attributes from it, this should be enough. Otherwise (if attributes and their values are required), it should be written into [2-dimensional array](https://github.com/Vitaliy-1/JATSParser/blob/5b9affcaffc836675d04cf5c6b67543641e9717b/src/JATSParser/Body/Text.php#L62). 

I'm also thinking about making the procedure of adding new elements easier. But that's would be after docx2jats converter will be ready.

**Comment by josuevalrob** [comment]
good.!
About docx2jats, my team did this to create jats documents: 
[convertidor](http://5.56.56.37/jats/)
Everything is javascript, so you can check the code. 

Now I am trying to create a kind of selector for inside the paragraph so you can add xref, bold, italic, etc.

**Comment by Vitaliy-1** [comment]
Great work!
By the way, have you looked at the Texture plugin that is now available from the plugin gallery? It's not fully ready but already can do many things as JATS wysiwyg editor. I haven't dived into its code yet, but it's looking quite promising,

**Comment by josuevalrob** [comment]
Oh, I will check it.
