### ISSUE TITLE
HTML Galley not show correctly

### ISSUE THREAD

**Issue by ericklanzas** [Vitaliy-1/oldGregg#95]
Sorry for my poor English. 
When I trying to create a galley in html, the styles are not applied, but default theme its OK.
![captura de pantalla 378](https://user-images.githubusercontent.com/37481107/49963075-9e7c3300-fedc-11e8-8d9c-63d324bb4909.png)

You can see the article on:
https://www.revistarecientec.unan.edu.ni/index.php/recientec/article/view/3/4

**Comment by ericklanzas** [comment]
Sorry for my poor English. 
When I trying to create a galley in html, the styles are not applied, but default theme its OK.
![captura de pantalla 378](https://user-images.githubusercontent.com/37481107/49963075-9e7c3300-fedc-11e8-8d9c-63d324bb4909.png)

**Comment by ericklanzas** [comment]
https://www.revistarecientec.unan.edu.ni/index.php/recientec/article/view/3/4

**Comment by Vitaliy-1** [comment]
Hi @ericklanzas 
The theme just wasn't designed for that. It renders JATS XML in the first place. But I'll add styles for HTML Galleys later, after finishing the work on the DOCX to JATS XML converter plugin for OJS 3

**Comment by ericklanzas** [comment]
Thanks @Vitaliy-1  for the clarification.
Now I understand !! the theme is fantastic!... thanks for reply!!
