### ISSUE TITLE
nav content is missing 

### ISSUE THREAD

**Issue by syaiful-scooter** [Vitaliy-1/oldGregg#97]
@Vitaliy-1 
how to add content tab on article page, do i missed something?
 
![1-8-2019 10-23-37 pm](https://user-images.githubusercontent.com/20450452/50840249-a1abf700-1394-11e9-8e38-9077fad10fdc.png)

**Comment by Vitaliy-1** [comment]
Hi @syaiful-scooter 

The content tab is shown only if an article has JATS XML galley downloaded. It cannot parse section titles from PDFs.
